name: "Beta Preview" 
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: "3.1.101"
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    
    - name: "Setup dotnet ${{ env.DOTNET_VERSION }}"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: "Restore"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --configuration Release --no-restore

    - name: "Test"
      run: dotnet test --no-restore --verbosity normal
    
    - name: "Publish Functions"
      run: dotnet publish ./MotoHealth.Functions/MotoHealth.Functions.csproj --no-build --configuration Release --output ${{ env.OUTPUT_PATH }}/functions
      
    - name: "Upload Functions Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}/functions

    - name: "Publish Bot"
      run: dotnet publish ./MotoHealth.Bot/MotoHealth.Bot.csproj --no-build --configuration Release --output ${{ env.OUTPUT_PATH }}/bot
      
    - name: "Upload Bot Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: bot
        path: ${{ env.OUTPUT_PATH }}/bot
        
  deploy-functions:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}/functions

      - name: "Deploy"
        uses: Azure/functions-action@v1.1.4
        with:
          app-name: ${{ secrets.BETA_FUNC_APP_NAME }}
          package: ${{ env.OUTPUT_PATH }}/functions
          publish-profile: ${{ secrets.BETA_FUNC_APP_SCM_CREDENTIALS }}
  
  deploy-bot:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v1
          with:
            name: bot
            path: ${{ env.OUTPUT_PATH }}/bot
      
      - name: "Deploy"
        uses: "azure/webapps-deploy@v2"
        with:
          app-name: ${{ secrets.BETA_BOT_APP_NAME }}
          package: ${{ env.OUTPUT_PATH }}/bot
          publish-profile: ${{ secrets.BETA_BOT_APP_SCM_CREDENTIALS }}



        
